apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postfix-dovecot-deployment.yaml

configMapGenerator:
  - name: postfix-dovecot-config
    literals:
      - POSTFIX_DOMAIN=<YOUR_DOMAIN>
      - MAIL_HOSTNAME=<YOUR_MAIL_HOSTNAME>
      - POSTFIX_POSTMASTER=postmaster
